version: "3.9"

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable

    privileged: true                      # Required for access to USB and camera devices
    restart: unless-stopped              # Restart automatically unless manually stopped
    network_mode: host                   # Use host network for direct access and performance

    shm_size: "128mb"                    # Shared memory allocation for video buffering

    environment:
      FRIGATE_RTSP_PASSWORD: "your_real_secure_password_here"  # RTSP stream protection

    volumes:
      - /etc/localtime:/etc/localtime:ro             # Sync container time with host
      - ./config.yml:/config/config.yml              # Mount Frigate config file
      - /media/frigate_storage:/media/frigate        # USB drive for storage
      - type: tmpfs
        target: /tmp/cache                           # Use RAM for temporary cache
        tmpfs:
          size: 1000000000                           # 1GB

    devices:
      - /dev/bus/usb:/dev/bus/usb                    # USB devices (e.g., Coral)
      - /dev/dri/renderD128:/dev/dri/renderD128      # GPU device for video acceleration
      # Uncomment and add additional video devices if necessary:
      # - /dev/video10:/dev/video10
      # - /dev/video11:/dev/video11
      # - /dev/video12:/dev/video12

# Frigate Web UI available at http://<RASPBERRY_PI_IP>:5000
